backend:
  name: github
  repo: robrev/hugotest # Path to your Github repository
  branch: master # Branch to update
publish_mode: editorial_workflow
media_folder: "static/images" # Media files will be stored in the repo under images/uploads
public_folder: "/images"
collections:
  - name: "post"
    label: "Posts"
    folder: "/content/post"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}